### ISSUE TITLE
Contribution path

### ISSUE THREAD

**Issue by ealves-pt** [grevory/angular-local-storage#282]
Hi everyone,

So, after grooming the existing issue I came up with the following items that might require some action in the future.

### Bugs
- [ ] localStorage not persistant in Cordova (#202)
- [ ] Problem returning non-JSON values (#230)
- [ ] Error when storing dates (#241)
- [ ] Set cookie expiration to 0 (#250)

### Enhancement
- [ ] Support for selecting type of storage on the fly (#151, #192, #231, #270, #281)
- [ ] Allow to store session cookies (#246)
- [ ] get a non-existing key should return `undefined` and not `null` (#245)
- [ ] set a prefix at run-time (#176)
- [ ] include source maps (#139)
- [ ] throw exception if exceeds quota (#110)
- [ ] support secure cookies (#272)

### Features
- [ ] Specify when and how to use fallbacks (#168, #237)
- [ ] Add support for TTL on keys (#239)
- [ ] Sync values between different tabs (#199)
- [ ] Add support for other storage types (#257)

### Nice to have
- [ ] Upload to a CDN (#210)

### Proposals
- [ ] Migrate source code to TypeScript and publish the API definitions on [typings](https://github.com/typings/typings). This change must be backwards compatible.
- [ ] Rewrite the entire module to tackle requested enhancements and features.

I will wait for some feedback. :smiley:

**Comment by grevory** [comment]
My first thought is that many of these bugs / enhancements can be fixed without rewrite. I think we need to start there.

**Comment by ealves-pt** [comment]
@grevory you are right, a good number of these issues can be solved without changing many things. Meanwhile to start taking a look at the pending PR can you give me your feedback on PR #279.

**Comment by ealves-pt** [comment]
I have marked some enhancements as **breaking changes** because those will require some changes in the API.
